title: Alejandro López
logo: /assets/img/headshot_circle2.jpg
description: 🔌 A Electrical Engineer and Data analyst  with specialized experience in the electrical sector. I have applied my deep knowledge of distribution electrical systems to solve complex problems and improve efficiency.
show_downloads: False
theme: jekyll-theme-minimal
