title: Alejandro López Aguirre
#logo: /assets/img/headshot_circle.png
description: Electrical Engineering Master specializing in data analytics with Python. Expert in optimizing diverse problems.
show_downloads: False
theme: jekyll-theme-minimal
